# Generated by Django 5.2.14 on 2026-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityrecord',
            old_name='activity_date',
            new_name='activity_date_start',
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='activity_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='source_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='after_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='before_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
